title:              Sakthiprian
email:              sakthiprians@gmail.com
description:        Personal site
author:             Sakthiprian
baseurl:            "personal-site"
url:                "https://sakthiprian.github.io"
# Social Profiles
twitter_username:   
github_username:    Sakthiprian
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
remote_theme: clean-blog
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
